update to use storage account for state file

diff --git a/.github/workflows/organizations.yml b/.github/workflows/organizations.yml
--- a/.github/workflows/organizations.yml
+++ b/.github/workflows/organizations.yml
@@ -8,6 +8,14 @@ on:
     branches:
       - main
 
+env:
+  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
+  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+  github_token: ${{ secrets.ORG_CREATE_TOKEN }}
+  github_enterprise_slug: TyroneTyrone
+  TF_LOG: "DEBUG"  
+      
 jobs:
   terraform:
     runs-on: ubuntu-latest
@@ -25,21 +33,31 @@ jobs:
       with:
         terraform_version: 1.10.5
 
+
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # Will fail the build if not
+    - name: Terraform Format
+      run: terraform fmt -check
+
     - name: Terraform Init
-      env:
-        TF_LOG: "DEBUG"
-        github_token: ${{ secrets.ORG_CREATE_TOKEN }}
-        github_enterprise_slug: TyroneTyrone
       run: |
         terraform init 
 
     - name: Terraform Plan
-      env:
-        TF_LOG: "DEBUG"
-        github_token: ${{ secrets.ORG_CREATE_TOKEN }}
-        github_enterprise_slug: TyroneTyrone
       run: |
-        terraform plan -var "github_enterprise_slug=TyroneTyrone" -var "github_token=${{ secrets.ORG_CREATE_TOKEN }}" -out=tfplan
+        terraform plan \
+         -var "github_enterprise_slug=TyroneTyrone" \
+         -var "github_token=${{ secrets.ORG_CREATE_TOKEN }}" \
+         -out=tfplan || export exitcode=$?
+        
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi            
         
     - name: Terraform Apply
       if: github.ref == 'refs/heads/main'
